### ISSUE TITLE
Formato do Arquivo

### ISSUE THREAD

**Issue by mensonones** [AllefLobo/npi-autoestudos-contatos#1]
Porque não deixa a estrutura do projeto aberta? Ás vezes a galera só quer olhar e não baixar. É uma dica. :+1:

**Comment by AllefLobo** [comment]
Tive alguns problemas ao fazer o pull, e mandei da maneira que fosse pois eu só precisava pegar depois.
Depois vou consertar isso.

**Comment by AllefLobo** [comment]
Fiz o upload do arquivo descompactado.
